services:
  dev-web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f /tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"  ## start rails server
    volumes:
      - .:/rails                                                                       ## default rails container app dir
    ports:
      - "8008:3000"                                                                    ## allow us to access app on port 8008
